import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

import { presidents_fr } from '../services/presidents_fr';
import { presidents_ja } from '../services/presidents_ja';
import { presidents_ar } from '../services/presidents_ar';
import { presidents_hi } from '../services/presidents_hi';
import { presidents_es } from '../services/presidents_es';
import { presidents_zh } from '../services/presidents_zh';

export type Language = 'en' | 'fr' | 'ja' | 'ar' | 'hi' | 'es' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  getPresidentTranslation: (id: number, field: 'title' | 'context', fallback: string) => string;
}

const translations = {
  en: {
    'start.title': 'Presidential Timeline',
    'start.subtitle': 'Test your knowledge of American leaders.',
    'start.learn': 'Learn',
    'start.howToPlay': 'How to Play',
    'start.reviewMode': 'Review Mode',
    'start.play': 'Play',
    'start.guessPresident': 'Guess President',
    'start.guessYear': 'Guess Year',
    'start.guessSuccessor': 'Guess Successor',
    'start.privacyPolicy': 'Privacy Policy',
    'start.termsOfService': 'Terms of Service',
    'start.feedback': 'Feedback',
    'start.hallOfFame': 'Hall of Fame',
    'game.placePresident': 'Place {name} on the timeline.',
    'game.whoWasSuccessor': 'Who was the successor to {name}?',
    'fact.whoIsThis': 'Who is this?',
    'game.year': 'Year',
    'game.submit': 'Submit',
    'scoreboard.score': 'Score: {score}',
    'scoreboard.incorrect': 'Incorrect: {incorrect}',
    'scoreboard.round': 'Round {round} of {totalRounds}',
    'scoreboard.time': 'Time: {time}s',
    'end.gameOver': 'Game Over!',
    'end.finalScore': 'Final Score: {score} / {totalRounds}',
    'end.totalTimeLeft': 'Total Time Left: {time}s',
    'end.enterName': 'Enter your name for the Hall of Fame:',
    'end.submitScore': 'Submit Score',
    'end.playAgain': 'Play Again',
    'end.saving': 'Saving...',
    'end.globalTop10': 'Global Top 10! 🏆',
    'end.greatEffort': 'Great effort! Try again to reach the global Top 10.',
    'feedback.correct': 'Correct!',
    'feedback.incorrect': 'Incorrect!',
    'feedback.timeUp': 'Time\'s Up!',
    'feedback.yearWas': 'The year was {year}.',
    'feedback.successorWas': 'The successor was {name}.',
    'feedback.presidentWas': 'The president was {name}.',
    'feedback.yearCorrectDesc': 'You were right on the money! The term began in {year}.',
    'feedback.yearIncorrectDesc': 'You guessed {guessed}, but the correct year was ',
    'feedback.successorCorrectDesc': '{name} was indeed the next president.',
    'feedback.successorIncorrectDesc': 'You guessed {guessed}, but the correct successor was ',
    'feedback.presidentCorrectDesc': 'That\'s right! It was {name}.',
    'feedback.presidentIncorrectDesc': 'You guessed {guessed}, but the correct president was ',
    'feedback.didYouKnow': 'Did you know?',
    'feedback.unknownPresident': 'an unknown president',
    'feedback.unknown': 'Unknown',
    'feedback.nextRound': 'Next Round',
    'feedback.learnMore': 'Learn More',
    'feedback.stopPlaying': 'Stop Playing',
    'instructions.title': 'How to Play',
    'instructions.guessYear': 'Guess Year: Type the year the president started their term.',
    'instructions.guessSuccessor': 'Guess Successor: Select the president who came next.',
    'instructions.guessPresident': 'Guess President: Identify the president based on the clue.',
    'instructions.close': 'Close',
    'leaderboard.title': 'Hall of Fame',
    'leaderboard.loading': 'Loading...',
    'leaderboard.noScores': 'No scores yet. Be the first!',
    'leaderboard.rank': 'Rank',
    'leaderboard.name': 'Name',
    'leaderboard.score': 'Score',
    'leaderboard.time': 'Time Left',
    'leaderboard.date': 'Date',
    'leaderboard.mode': 'Mode',
    'leaderboard.back': 'Back to Start',
    'review.title': 'Review Mode',
    'review.back': 'Back to Start',
    'review.search': 'Search presidents...',
    'review.term': 'Term: {start} - {end}',
    'review.noResults': 'No Presidents Found',
    'review.adjustFilters': 'Try adjusting your filters.',
    'review.searchName': '1. Search Name',
    'review.searchNamePlaceholder': 'e.g., Lincoln',
    'review.searchDates': '2. Search from and to date',
    'review.searchFrom': 'From (e.g., 1800)',
    'review.searchTo': 'To (e.g., 1850)',
    'review.searchPeriod': '3. Search Period',
    'review.allPeriods': 'All Periods',
    'review.clearFilters': 'Clear Filters',
    'review.cancel': 'Cancel',
    'review.apply': 'Apply',
    'review.advancedSearch': 'Advanced Search',
    'review.searchAndFilter': 'Search & Filter',
    'review.foundResults': 'Found {count} result(s). Click a card to learn more.',
    'review.hoverToPause': 'Hover to pause, or click a card to learn more.',
    'review.speed': 'Speed',
    'review.noPortrait': 'No Portrait',
    'review.present': 'Present',
    'card.lessThanYear': '(less than a year)',
    'card.years': '({duration} year{s})',
    'card.yearsAndCounting': '({duration} year{s} and counting)',
    'card.portraitNotAvailable': 'Portrait not available',
    'card.pending': 'PENDING',
    'card.changePortrait': 'Change Portrait',
    'seal.notAvailable': 'Seal not available',
    'seal.changeImage': 'Change Image',
    'privacy.title': 'Privacy Policy',
    'privacy.back': 'Back to Start',
    'privacy.lastUpdated': 'Last updated: October 26, 2023',
    'privacy.p1': 'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.',
    'privacy.h1': 'Interpretation and Definitions',
    'privacy.p2': 'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
    'privacy.h2': 'Collecting and Using Your Personal Data',
    'privacy.p3': 'We do not collect any personal data. This application acts as a client-side game. Game progress is stored temporarily in your browser\'s memory while you play.',
    'privacy.h3': 'API Usage',
    'privacy.p4': 'This application uses Google Gemini API for generating historical content. When you use the "Learn More" feature, the application sends a prompt to the API. No personal user data is sent.',
    'privacy.h4': 'Contact Us',
    'privacy.p5': 'If you have any questions about this Privacy Policy, You can contact us.',
    'terms.title': 'Terms of Service',
    'terms.back': 'Back to Start',
    'terms.lastUpdated': 'Last updated: October 26, 2023',
    'terms.p1': 'Please read these terms and conditions carefully before using Our Service.',
    'terms.h1': 'Acknowledgment',
    'terms.p2': 'These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.',
    'terms.h2': 'Content',
    'terms.p3': 'The historical data presented in this game is for entertainment and educational purposes. While we strive for accuracy, we cannot guarantee that all information is perfectly accurate or up-to-date.',
    'terms.h3': 'Intellectual Property',
    'terms.p4': 'The Service and its original content, features and functionality are and will remain the exclusive property of the Company and its licensors.',
    'terms.h4': 'Termination',
    'terms.p5': 'We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.',
    'rag.loading': 'Loading...',
    'rag.close': 'Close',
    'rag.error': 'Error fetching data.',
    'rag.errorDetailed': 'Sorry, I couldn\'t fetch more information at this time. Please check your API key and network connection.',
    'rag.findingInfo': 'Finding some brilliant information on',
    'rag.pleaseWait': 'for you... please wait.',
    'rag.sources': 'Sources',
    'rag.translate': 'Translate',
    'rag.translating': 'Translating...',
    'fact.selectPresident': 'Select a president...',
    'timeline.correct': 'Correct: {year}',
    'timeline.yourGuess': 'Your Guess: {year}',
    'period.earlyRepublic': 'Early Republic',
    'period.civilWar': 'Civil War & Industrialization',
    'period.americanCentury': 'The American Century',
    'period.modernAmerica': 'Modern America',
  },
  fr: {
    'start.title': 'Chronologie Présidentielle',
    'start.subtitle': 'Testez vos connaissances sur les dirigeants américains.',
    'start.learn': 'Apprendre',
    'start.howToPlay': 'Comment jouer',
    'start.reviewMode': 'Mode Révision',
    'start.play': 'Jouer',
    'start.guessPresident': 'Deviner le Président',
    'start.guessYear': 'Deviner l\'Année',
    'start.guessSuccessor': 'Deviner le Successeur',
    'start.privacyPolicy': 'Politique de Confidentialité',
    'start.termsOfService': 'Conditions d\'Utilisation',
    'start.feedback': 'Commentaires',
    'start.hallOfFame': 'Panthéon',
    'game.placePresident': 'Placez {name} sur la chronologie.',
    'game.whoWasSuccessor': 'Qui était le successeur de {name} ?',
    'fact.whoIsThis': 'Qui est-ce ?',
    'game.year': 'Année',
    'game.submit': 'Soumettre',
    'scoreboard.score': 'Score : {score}',
    'scoreboard.incorrect': 'Incorrect : {incorrect}',
    'scoreboard.round': 'Manche {round} sur {totalRounds}',
    'scoreboard.time': 'Temps : {time}s',
    'end.gameOver': 'Fin du Jeu !',
    'end.finalScore': 'Score Final : {score} / {totalRounds}',
    'end.totalTimeLeft': 'Temps Restant Total : {time}s',
    'end.enterName': 'Entrez votre nom pour le Panthéon :',
    'end.submitScore': 'Soumettre le Score',
    'end.playAgain': 'Rejouer',
    'end.saving': 'Enregistrement...',
    'end.globalTop10': 'Top 10 Mondial ! 🏆',
    'end.greatEffort': 'Bel effort ! Réessayez pour atteindre le Top 10 mondial.',
    'feedback.correct': 'Correct !',
    'feedback.incorrect': 'Incorrect !',
    'feedback.timeUp': 'Temps Écoulé !',
    'feedback.yearWas': 'L\'année était {year}.',
    'feedback.successorWas': 'Le successeur était {name}.',
    'feedback.presidentWas': 'Le président était {name}.',
    'feedback.yearCorrectDesc': 'Vous avez vu juste ! Le mandat a commencé en {year}.',
    'feedback.yearIncorrectDesc': 'Vous avez deviné {guessed}, mais l\'année correcte était ',
    'feedback.successorCorrectDesc': '{name} était bien le président suivant.',
    'feedback.successorIncorrectDesc': 'Vous avez deviné {guessed}, mais le successeur correct était ',
    'feedback.presidentCorrectDesc': 'C\'est exact ! C\'était {name}.',
    'feedback.presidentIncorrectDesc': 'Vous avez deviné {guessed}, mais le président correct était ',
    'feedback.didYouKnow': 'Le saviez-vous ?',
    'feedback.unknownPresident': 'un président inconnu',
    'feedback.unknown': 'Inconnu',
    'feedback.nextRound': 'Manche Suivante',
    'feedback.learnMore': 'En Savoir Plus',
    'feedback.stopPlaying': 'Arrêter de Jouer',
    'instructions.title': 'Comment Jouer',
    'instructions.guessYear': 'Deviner l\'Année : Tapez l\'année où le président a commencé son mandat.',
    'instructions.guessSuccessor': 'Deviner le Successeur : Sélectionnez le président qui a suivi.',
    'instructions.guessPresident': 'Deviner le Président : Identifiez le président d\'après l\'indice.',
    'instructions.close': 'Fermer',
    'leaderboard.title': 'Panthéon',
    'leaderboard.loading': 'Chargement...',
    'leaderboard.noScores': 'Aucun score pour le moment. Soyez le premier !',
    'leaderboard.rank': 'Rang',
    'leaderboard.name': 'Nom',
    'leaderboard.score': 'Score',
    'leaderboard.time': 'Temps Restant',
    'leaderboard.date': 'Date',
    'leaderboard.mode': 'Mode',
    'leaderboard.back': 'Retour à l\'Accueil',
    'review.title': 'Mode Révision',
    'review.back': 'Retour à l\'Accueil',
    'review.search': 'Rechercher des présidents...',
    'review.term': 'Mandat : {start} - {end}',
    'review.noResults': 'Aucun président trouvé',
    'review.adjustFilters': 'Essayez de modifier vos filtres.',
    'review.searchName': '1. Rechercher par nom',
    'review.searchNamePlaceholder': 'ex. Lincoln',
    'review.searchDates': '2. Rechercher de date à date',
    'review.searchFrom': 'De (ex. 1800)',
    'review.searchTo': 'À (ex. 1850)',
    'review.searchPeriod': '3. Période de recherche',
    'review.allPeriods': 'Toutes les périodes',
    'review.clearFilters': 'Effacer les filtres',
    'review.cancel': 'Annuler',
    'review.apply': 'Appliquer',
    'review.advancedSearch': 'Recherche avancée',
    'review.searchAndFilter': 'Rechercher et filtrer',
    'review.foundResults': '{count} résultat(s) trouvé(s). Cliquez sur une carte pour en savoir plus.',
    'review.hoverToPause': 'Survolez pour mettre en pause, ou cliquez sur une carte pour en savoir plus.',
    'review.speed': 'Vitesse',
    'review.noPortrait': 'Pas de portrait',
    'review.present': 'Présent',
    'card.lessThanYear': '(moins d\'un an)',
    'card.years': '({duration} an{s})',
    'card.yearsAndCounting': '({duration} an{s} et ça continue)',
    'card.portraitNotAvailable': 'Portrait non disponible',
    'card.pending': 'EN ATTENTE',
    'card.changePortrait': 'Changer le portrait',
    'seal.notAvailable': 'Sceau non disponible',
    'seal.changeImage': 'Changer l\'image',
    'privacy.title': 'Politique de Confidentialité',
    'privacy.back': 'Retour à l\'Accueil',
    'privacy.lastUpdated': 'Dernière mise à jour : 26 octobre 2023',
    'privacy.p1': 'Cette politique de confidentialité décrit nos politiques et procédures sur la collecte, l\'utilisation et la divulgation de vos informations lorsque vous utilisez le service et vous informe de vos droits à la confidentialité et de la façon dont la loi vous protège.',
    'privacy.h1': 'Interprétation et Définitions',
    'privacy.p2': 'Les mots dont la lettre initiale est en majuscule ont des significations définies dans les conditions suivantes. Les définitions suivantes auront la même signification, qu\'elles apparaissent au singulier ou au pluriel.',
    'privacy.h2': 'Collecte et Utilisation de Vos Données Personnelles',
    'privacy.p3': 'Nous ne collectons aucune donnée personnelle. Cette application agit comme un jeu côté client. La progression du jeu est stockée temporairement dans la mémoire de votre navigateur pendant que vous jouez.',
    'privacy.h3': 'Utilisation de l\'API',
    'privacy.p4': 'Cette application utilise l\'API Google Gemini pour générer du contenu historique. Lorsque vous utilisez la fonction "En Savoir Plus", l\'application envoie une invite à l\'API. Aucune donnée utilisateur personnelle n\'est envoyée.',
    'privacy.h4': 'Nous Contacter',
    'privacy.p5': 'Si vous avez des questions sur cette politique de confidentialité, vous pouvez nous contacter.',
    'terms.title': 'Conditions d\'Utilisation',
    'terms.back': 'Retour à l\'Accueil',
    'terms.lastUpdated': 'Dernière mise à jour : 26 octobre 2023',
    'terms.p1': 'Veuillez lire attentivement ces conditions générales avant d\'utiliser notre service.',
    'terms.h1': 'Reconnaissance',
    'terms.p2': 'Ce sont les conditions générales régissant l\'utilisation de ce service et l\'accord qui opère entre vous et la société. Ces conditions générales définissent les droits et obligations de tous les utilisateurs concernant l\'utilisation du service.',
    'terms.h2': 'Contenu',
    'terms.p3': 'Les données historiques présentées dans ce jeu sont à des fins de divertissement et d\'éducation. Bien que nous nous efforcions d\'être précis, nous ne pouvons garantir que toutes les informations sont parfaitement exactes ou à jour.',
    'terms.h3': 'Propriété Intellectuelle',
    'terms.p4': 'Le service et son contenu original, ses caractéristiques et ses fonctionnalités sont et resteront la propriété exclusive de la société et de ses concédants de licence.',
    'terms.h4': 'Résiliation',
    'terms.p5': 'Nous pouvons résilier ou suspendre votre accès immédiatement, sans préavis ni responsabilité, pour quelque raison que ce soit, y compris sans s\'y limiter si vous enfreignez ces conditions générales.',
    'rag.loading': 'Chargement...',
    'rag.close': 'Fermer',
    'rag.error': 'Erreur lors de la récupération des données.',
    'rag.errorDetailed': 'Désolé, je n\'ai pas pu récupérer plus d\'informations pour le moment. Veuillez vérifier votre clé API et votre connexion réseau.',
    'rag.findingInfo': 'Recherche d\'informations brillantes sur',
    'rag.pleaseWait': 'pour vous... veuillez patienter.',
    'rag.sources': 'Sources',
    'rag.translate': 'Traduire',
    'rag.translating': 'Traduction en cours...',
    'fact.selectPresident': 'Sélectionnez un président...',
    'timeline.correct': 'Correct : {year}',
    'timeline.yourGuess': 'Votre estimation : {year}',
    'period.earlyRepublic': 'Première République',
    'period.civilWar': 'Guerre de Sécession et Industrialisation',
    'period.americanCentury': 'Le Siècle Américain',
    'period.modernAmerica': 'L\'Amérique Moderne',
  },
  ja: {
    'start.title': '大統領のタイムライン',
    'start.subtitle': 'アメリカの指導者に関する知識をテストしましょう。',
    'start.learn': '学ぶ',
    'start.howToPlay': '遊び方',
    'start.reviewMode': 'レビューモード',
    'start.play': 'プレイ',
    'start.guessPresident': '大統領を当てる',
    'start.guessYear': '年を当てる',
    'start.guessSuccessor': '後継者を当てる',
    'start.privacyPolicy': 'プライバシーポリシー',
    'start.termsOfService': '利用規約',
    'start.feedback': 'フィードバック',
    'start.hallOfFame': '殿堂入り',
    'game.placePresident': '{name}をタイムラインに配置してください。',
    'game.whoWasSuccessor': '{name}の後継者は誰ですか？',
    'fact.whoIsThis': 'これは誰ですか？',
    'game.year': '年',
    'game.submit': '送信',
    'scoreboard.score': 'スコア: {score}',
    'scoreboard.incorrect': '不正解: {incorrect}',
    'scoreboard.round': 'ラウンド {round} / {totalRounds}',
    'scoreboard.time': '時間: {time}秒',
    'end.gameOver': 'ゲームオーバー！',
    'end.finalScore': '最終スコア: {score} / {totalRounds}',
    'end.totalTimeLeft': '残り時間合計: {time}秒',
    'end.enterName': '殿堂入りに名前を入力してください:',
    'end.submitScore': 'スコアを送信',
    'end.playAgain': 'もう一度プレイ',
    'end.saving': '保存中...',
    'end.globalTop10': 'グローバルトップ10！ 🏆',
    'end.greatEffort': 'よく頑張りました！グローバルトップ10を目指してもう一度挑戦してください。',
    'feedback.correct': '正解！',
    'feedback.incorrect': '不正解！',
    'feedback.timeUp': '時間切れ！',
    'feedback.yearWas': '年は{year}年でした。',
    'feedback.successorWas': '後継者は{name}でした。',
    'feedback.presidentWas': '大統領は{name}でした。',
    'feedback.yearCorrectDesc': '大正解！任期は{year}年に始まりました。',
    'feedback.yearIncorrectDesc': 'あなたの予想は{guessed}年でしたが、正解は',
    'feedback.successorCorrectDesc': 'その通り！次の大統領は{name}でした。',
    'feedback.successorIncorrectDesc': 'あなたの予想は{guessed}でしたが、正解は',
    'feedback.presidentCorrectDesc': 'その通り！{name}でした。',
    'feedback.presidentIncorrectDesc': 'あなたの予想は{guessed}でしたが、正解は',
    'feedback.didYouKnow': '知っていましたか？',
    'feedback.unknownPresident': '不明な大統領',
    'feedback.unknown': '不明',
    'feedback.nextRound': '次のラウンド',
    'feedback.learnMore': 'もっと詳しく',
    'feedback.stopPlaying': 'プレイをやめる',
    'instructions.title': '遊び方',
    'instructions.guessYear': '年を当てる: 大統領が任期を開始した年を入力します。',
    'instructions.guessSuccessor': '後継者を当てる: 次に就任した大統領を選択します。',
    'instructions.guessPresident': '大統領を当てる: ヒントに基づいて大統領を特定します。',
    'instructions.close': '閉じる',
    'leaderboard.title': '殿堂入り',
    'leaderboard.loading': '読み込み中...',
    'leaderboard.noScores': 'まだスコアがありません。最初のプレイヤーになりましょう！',
    'leaderboard.rank': '順位',
    'leaderboard.name': '名前',
    'leaderboard.score': 'スコア',
    'leaderboard.time': '残り時間',
    'leaderboard.date': '日付',
    'leaderboard.mode': 'モード',
    'leaderboard.back': 'スタートに戻る',
    'review.title': 'レビューモード',
    'review.back': 'スタートに戻る',
    'review.search': '大統領を検索...',
    'review.term': '任期: {start} - {end}',
    'review.noResults': '大統領が見つかりません',
    'review.adjustFilters': 'フィルターを調整してみてください。',
    'review.searchName': '1. 名前で検索',
    'review.searchNamePlaceholder': '例: リンカーン',
    'review.searchDates': '2. 期間で検索',
    'review.searchFrom': '開始（例: 1800）',
    'review.searchTo': '終了（例: 1850）',
    'review.searchPeriod': '3. 時代で検索',
    'review.allPeriods': 'すべての時代',
    'review.clearFilters': 'フィルターをクリア',
    'review.cancel': 'キャンセル',
    'review.apply': '適用',
    'review.advancedSearch': '高度な検索',
    'review.searchAndFilter': '検索とフィルター',
    'review.foundResults': '{count}件の結果が見つかりました。カードをクリックして詳細を表示します。',
    'review.hoverToPause': 'ホバーして一時停止するか、カードをクリックして詳細を表示します。',
    'review.speed': '速度',
    'review.noPortrait': '肖像画なし',
    'review.present': '現在',
    'card.lessThanYear': '（1年未満）',
    'card.years': '（{duration}年）',
    'card.yearsAndCounting': '（{duration}年目）',
    'card.portraitNotAvailable': '肖像画は利用できません',
    'card.pending': '保留中',
    'card.changePortrait': '肖像画を変更',
    'seal.notAvailable': '紋章は利用できません',
    'seal.changeImage': '画像を変更',
    'privacy.title': 'プライバシーポリシー',
    'privacy.back': 'スタートに戻る',
    'privacy.lastUpdated': '最終更新日: 2023年10月26日',
    'privacy.p1': 'このプライバシーポリシーは、お客様が本サービスを利用する際の情報収集、使用、開示に関する当社のポリシーと手順を説明し、お客様のプライバシーの権利と法律がお客様をどのように保護するかについてお知らせするものです。',
    'privacy.h1': '解釈と定義',
    'privacy.p2': '頭文字が大文字の単語は、以下の条件で定義された意味を持ちます。以下の定義は、単数形でも複数形でも同じ意味を持つものとします。',
    'privacy.h2': '個人データの収集と使用',
    'privacy.p3': '当社は個人データを収集しません。このアプリケーションはクライアントサイドのゲームとして機能します。ゲームの進行状況は、プレイ中にお使いのブラウザのメモリに一時的に保存されます。',
    'privacy.h3': 'APIの使用',
    'privacy.p4': 'このアプリケーションは、歴史的コンテンツの生成にGoogle Gemini APIを使用しています。「もっと詳しく」機能を使用すると、アプリケーションはAPIにプロンプトを送信します。個人のユーザーデータは送信されません。',
    'privacy.h4': 'お問い合わせ',
    'privacy.p5': 'このプライバシーポリシーについてご質問がある場合は、お問い合わせください。',
    'terms.title': '利用規約',
    'terms.back': 'スタートに戻る',
    'terms.lastUpdated': '最終更新日: 2023年10月26日',
    'terms.p1': '当社のサービスを利用する前に、これらの利用規約をよくお読みください。',
    'terms.h1': '承認',
    'terms.p2': 'これらは、本サービスの利用およびお客様と当社との間で運用される合意を規定する利用規約です。これらの利用規約は、本サービスの利用に関するすべてのユーザーの権利と義務を定めています。',
    'terms.h2': 'コンテンツ',
    'terms.p3': 'このゲームで提示される歴史的データは、娯楽および教育目的のものです。正確性を期すよう努めていますが、すべての情報が完全に正確または最新であることを保証するものではありません。',
    'terms.h3': '知的財産',
    'terms.p4': '本サービスおよびその元のコンテンツ、機能、機能性は、当社およびそのライセンサーの独占的財産であり、今後もそうあり続けます。',
    'terms.h4': '終了',
    'terms.p5': '当社は、お客様がこれらの利用規約に違反した場合を含め、いかなる理由であれ、事前の通知や責任を負うことなく、お客様のアクセスを直ちに終了または一時停止する場合があります。',
    'rag.loading': '読み込み中...',
    'rag.close': '閉じる',
    'rag.error': 'データの取得中にエラーが発生しました。',
    'rag.errorDetailed': '申し訳ありませんが、現時点では詳細情報を取得できませんでした。APIキーとネットワーク接続を確認してください。',
    'rag.findingInfo': '素晴らしい情報を探しています：',
    'rag.pleaseWait': '少々お待ちください...',
    'rag.sources': 'ソース',
    'rag.translate': '翻訳する',
    'rag.translating': '翻訳中...',
    'fact.selectPresident': '大統領を選択...',
    'timeline.correct': '正解: {year}',
    'timeline.yourGuess': 'あなたの予想: {year}',
    'period.earlyRepublic': '初期の共和国',
    'period.civilWar': '南北戦争と産業化',
    'period.americanCentury': 'アメリカの世紀',
    'period.modernAmerica': '現代のアメリカ',
  },
  ar: {
    'start.title': 'الجدول الزمني الرئاسي',
    'start.subtitle': 'اختبر معلوماتك عن القادة الأمريكيين.',
    'start.learn': 'تعلم',
    'start.howToPlay': 'كيف تلعب',
    'start.reviewMode': 'وضع المراجعة',
    'start.play': 'العب',
    'start.guessPresident': 'خمن الرئيس',
    'start.guessYear': 'خمن السنة',
    'start.guessSuccessor': 'خمن الخليفة',
    'start.privacyPolicy': 'سياسة الخصوصية',
    'start.termsOfService': 'شروط الخدمة',
    'start.feedback': 'ملاحظات',
    'start.hallOfFame': 'لوحة الشرف',
    'game.placePresident': 'ضع {name} على الجدول الزمني.',
    'game.whoWasSuccessor': 'من كان خليفة {name}؟',
    'fact.whoIsThis': 'من هذا؟',
    'game.year': 'السنة',
    'game.submit': 'إرسال',
    'scoreboard.score': 'النتيجة: {score}',
    'scoreboard.incorrect': 'غير صحيح: {incorrect}',
    'scoreboard.round': 'الجولة {round} من {totalRounds}',
    'scoreboard.time': 'الوقت: {time}ث',
    'end.gameOver': 'انتهت اللعبة!',
    'end.finalScore': 'النتيجة النهائية: {score} / {totalRounds}',
    'end.totalTimeLeft': 'إجمالي الوقت المتبقي: {time}ث',
    'end.enterName': 'أدخل اسمك للوحة الشرف:',
    'end.submitScore': 'إرسال النتيجة',
    'end.playAgain': 'العب مرة أخرى',
    'end.saving': 'جاري الحفظ...',
    'end.globalTop10': 'أفضل 10 عالمياً! 🏆',
    'end.greatEffort': 'مجهود رائع! حاول مرة أخرى للوصول إلى أفضل 10 عالمياً.',
    'feedback.correct': 'صحيح!',
    'feedback.incorrect': 'غير صحيح!',
    'feedback.timeUp': 'انتهى الوقت!',
    'feedback.yearWas': 'كانت السنة {year}.',
    'feedback.successorWas': 'كان الخليفة {name}.',
    'feedback.presidentWas': 'كان الرئيس {name}.',
    'feedback.yearCorrectDesc': 'أنت محق تماماً! بدأت الفترة في عام {year}.',
    'feedback.yearIncorrectDesc': 'لقد خمنت {guessed}، لكن السنة الصحيحة كانت ',
    'feedback.successorCorrectDesc': 'كان {name} بالفعل الرئيس التالي.',
    'feedback.successorIncorrectDesc': 'لقد خمنت {guessed}، لكن الخليفة الصحيح كان ',
    'feedback.presidentCorrectDesc': 'هذا صحيح! كان {name}.',
    'feedback.presidentIncorrectDesc': 'لقد خمنت {guessed}، لكن الرئيس الصحيح كان ',
    'feedback.didYouKnow': 'هل كنت تعلم؟',
    'feedback.unknownPresident': 'رئيس غير معروف',
    'feedback.unknown': 'غير معروف',
    'feedback.nextRound': 'الجولة التالية',
    'feedback.learnMore': 'اعرف المزيد',
    'feedback.stopPlaying': 'توقف عن اللعب',
    'instructions.title': 'كيف تلعب',
    'instructions.guessYear': 'خمن السنة: اكتب السنة التي بدأ فيها الرئيس فترته.',
    'instructions.guessSuccessor': 'خمن الخليفة: حدد الرئيس الذي جاء بعده.',
    'instructions.guessPresident': 'خمن الرئيس: حدد الرئيس بناءً على الدليل.',
    'instructions.close': 'إغلاق',
    'leaderboard.title': 'لوحة الشرف',
    'leaderboard.loading': 'جاري التحميل...',
    'leaderboard.noScores': 'لا توجد نتائج بعد. كن الأول!',
    'leaderboard.rank': 'المرتبة',
    'leaderboard.name': 'الاسم',
    'leaderboard.score': 'النتيجة',
    'leaderboard.time': 'الوقت المتبقي',
    'leaderboard.date': 'التاريخ',
    'leaderboard.mode': 'الوضع',
    'leaderboard.back': 'العودة للبداية',
    'review.title': 'وضع المراجعة',
    'review.back': 'العودة للبداية',
    'review.search': 'ابحث عن الرؤساء...',
    'review.term': 'الفترة: {start} - {end}',
    'review.noResults': 'لم يتم العثور على رؤساء',
    'review.adjustFilters': 'حاول تعديل عوامل التصفية الخاصة بك.',
    'review.searchName': '1. ابحث بالاسم',
    'review.searchNamePlaceholder': 'مثال، لينكولن',
    'review.searchDates': '2. ابحث من وإلى التاريخ',
    'review.searchFrom': 'من (مثال، 1800)',
    'review.searchTo': 'إلى (مثال، 1850)',
    'review.searchPeriod': '3. فترة البحث',
    'review.allPeriods': 'كل الفترات',
    'review.clearFilters': 'مسح عوامل التصفية',
    'review.cancel': 'إلغاء',
    'review.apply': 'تطبيق',
    'review.advancedSearch': 'بحث متقدم',
    'review.searchAndFilter': 'بحث وتصفية',
    'review.foundResults': 'تم العثور على {count} نتيجة. انقر على بطاقة لمعرفة المزيد.',
    'review.hoverToPause': 'مرر مؤشر الماوس للإيقاف المؤقت، أو انقر على بطاقة لمعرفة المزيد.',
    'review.speed': 'السرعة',
    'review.noPortrait': 'لا توجد صورة',
    'review.present': 'الحاضر',
    'card.lessThanYear': '(أقل من سنة)',
    'card.years': '({duration} سنة)',
    'card.yearsAndCounting': '({duration} سنة ومستمر)',
    'card.portraitNotAvailable': 'الصورة غير متوفرة',
    'card.pending': 'قيد الانتظار',
    'card.changePortrait': 'تغيير الصورة',
    'seal.notAvailable': 'الختم غير متوفر',
    'seal.changeImage': 'تغيير الصورة',
    'privacy.title': 'سياسة الخصوصية',
    'privacy.back': 'العودة للبداية',
    'privacy.lastUpdated': 'آخر تحديث: 26 أكتوبر 2023',
    'privacy.p1': 'تصف سياسة الخصوصية هذه سياساتنا وإجراءاتنا المتعلقة بجمع معلوماتك واستخدامها والكشف عنها عند استخدامك للخدمة وتخبرك بحقوق الخصوصية الخاصة بك وكيف يحميك القانون.',
    'privacy.h1': 'التفسير والتعاريف',
    'privacy.p2': 'الكلمات التي يكون الحرف الأول منها كبيراً لها معانٍ محددة في ظل الظروف التالية. يجب أن يكون للتعريفات التالية نفس المعنى بغض النظر عما إذا كانت تظهر بصيغة المفرد أو الجمع.',
    'privacy.h2': 'جمع واستخدام بياناتك الشخصية',
    'privacy.p3': 'نحن لا نجمع أي بيانات شخصية. يعمل هذا التطبيق كلعبة من جانب العميل. يتم تخزين تقدم اللعبة مؤقتاً في ذاكرة المتصفح الخاص بك أثناء اللعب.',
    'privacy.h3': 'استخدام واجهة برمجة التطبيقات (API)',
    'privacy.p4': 'يستخدم هذا التطبيق واجهة برمجة تطبيقات Google Gemini لإنشاء محتوى تاريخي. عند استخدام ميزة "اعرف المزيد"، يرسل التطبيق مطالبة إلى واجهة برمجة التطبيقات. لا يتم إرسال أي بيانات شخصية للمستخدم.',
    'privacy.h4': 'اتصل بنا',
    'privacy.p5': 'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يمكنك الاتصال بنا.',
    'terms.title': 'شروط الخدمة',
    'terms.back': 'العودة للبداية',
    'terms.lastUpdated': 'آخر تحديث: 26 أكتوبر 2023',
    'terms.p1': 'يرجى قراءة هذه الشروط والأحكام بعناية قبل استخدام خدمتنا.',
    'terms.h1': 'إقرار',
    'terms.p2': 'هذه هي الشروط والأحكام التي تحكم استخدام هذه الخدمة والاتفاقية التي تعمل بينك وبين الشركة. تحدد هذه الشروط والأحكام حقوق التزامات جميع المستخدمين فيما يتعلق باستخدام الخدمة.',
    'terms.h2': 'المحتوى',
    'terms.p3': 'البيانات التاريخية المقدمة في هذه اللعبة هي لأغراض الترفيه والتعليم. بينما نسعى جاهدين لتحقيق الدقة، لا يمكننا ضمان أن جميع المعلومات دقيقة تماماً أو محدثة.',
    'terms.h3': 'الملكية الفكرية',
    'terms.p4': 'الخدمة ومحتواها الأصلي وميزاتها ووظائفها هي وستظل ملكية حصرية للشركة ومرخصيها.',
    'terms.h4': 'الإنهاء',
    'terms.p5': 'يجوز لنا إنهاء أو تعليق وصولك على الفور، دون إشعار مسبق أو مسؤولية، لأي سبب من الأسباب، بما في ذلك على سبيل المثال لا الحصر إذا انتهكت هذه الشروط والأحكام.',
    'rag.loading': 'جاري التحميل...',
    'rag.close': 'إغلاق',
    'rag.error': 'خطأ في جلب البيانات.',
    'rag.errorDetailed': 'عذراً، لم أتمكن من جلب المزيد من المعلومات في هذا الوقت. يرجى التحقق من مفتاح API الخاص بك واتصال الشبكة.',
    'rag.findingInfo': 'البحث عن بعض المعلومات الرائعة حول',
    'rag.pleaseWait': 'من أجلك... يرجى الانتظار.',
    'rag.sources': 'المصادر',
    'rag.translate': 'ترجم',
    'rag.translating': 'جاري الترجمة...',
    'fact.selectPresident': 'حدد رئيساً...',
    'timeline.correct': 'صحيح: {year}',
    'timeline.yourGuess': 'تخمينك: {year}',
    'period.earlyRepublic': 'الجمهورية المبكرة',
    'period.civilWar': 'الحرب الأهلية والتصنيع',
    'period.americanCentury': 'القرن الأمريكي',
    'period.modernAmerica': 'أمريكا الحديثة',
  },
  hi: {
    'start.title': 'राष्ट्रपति समयरेखा',
    'start.subtitle': 'अमेरिकी नेताओं के बारे में अपने ज्ञान का परीक्षण करें।',
    'start.learn': 'सीखें',
    'start.howToPlay': 'कैसे खेलें',
    'start.reviewMode': 'समीक्षा मोड',
    'start.play': 'खेलें',
    'start.guessPresident': 'राष्ट्रपति का अनुमान लगाएं',
    'start.guessYear': 'वर्ष का अनुमान लगाएं',
    'start.guessSuccessor': 'उत्तराधिकारी का अनुमान लगाएं',
    'start.privacyPolicy': 'गोपनीयता नीति',
    'start.termsOfService': 'सेवा की शर्तें',
    'start.feedback': 'प्रतिक्रिया',
    'start.hallOfFame': 'हॉल ऑफ फेम',
    'game.placePresident': '{name} को समयरेखा पर रखें।',
    'game.whoWasSuccessor': '{name} का उत्तराधिकारी कौन था?',
    'fact.whoIsThis': 'यह कौन है?',
    'game.year': 'वर्ष',
    'game.submit': 'जमा करें',
    'scoreboard.score': 'स्कोर: {score}',
    'scoreboard.incorrect': 'गलत: {incorrect}',
    'scoreboard.round': 'राउंड {round} / {totalRounds}',
    'scoreboard.time': 'समय: {time}s',
    'end.gameOver': 'खेल खत्म!',
    'end.finalScore': 'अंतिम स्कोर: {score} / {totalRounds}',
    'end.totalTimeLeft': 'कुल समय शेष: {time}s',
    'end.enterName': 'हॉल ऑफ फेम के लिए अपना नाम दर्ज करें:',
    'end.submitScore': 'स्कोर जमा करें',
    'end.playAgain': 'फिर से खेलें',
    'end.saving': 'सहेजा जा रहा है...',
    'end.globalTop10': 'ग्लोबल टॉप 10! 🏆',
    'end.greatEffort': 'शानदार प्रयास! ग्लोबल टॉप 10 में पहुंचने के लिए फिर से प्रयास करें।',
    'feedback.correct': 'सही!',
    'feedback.incorrect': 'गलत!',
    'feedback.timeUp': 'समय समाप्त!',
    'feedback.yearWas': 'वर्ष {year} था।',
    'feedback.successorWas': 'उत्तराधिकारी {name} था।',
    'feedback.presidentWas': 'राष्ट्रपति {name} था।',
    'feedback.yearCorrectDesc': 'आप बिल्कुल सही हैं! कार्यकाल {year} में शुरू हुआ।',
    'feedback.yearIncorrectDesc': 'आपने {guessed} का अनुमान लगाया, लेकिन सही वर्ष था ',
    'feedback.successorCorrectDesc': '{name} वास्तव में अगले राष्ट्रपति थे।',
    'feedback.successorIncorrectDesc': 'आपने {guessed} का अनुमान लगाया, लेकिन सही उत्तराधिकारी था ',
    'feedback.presidentCorrectDesc': 'यह सही है! यह {name} था।',
    'feedback.presidentIncorrectDesc': 'आपने {guessed} का अनुमान लगाया, लेकिन सही राष्ट्रपति था ',
    'feedback.didYouKnow': 'क्या आप जानते हैं?',
    'feedback.unknownPresident': 'अज्ञात राष्ट्रपति',
    'feedback.unknown': 'अज्ञात',
    'feedback.nextRound': 'अगला राउंड',
    'feedback.learnMore': 'और जानें',
    'feedback.stopPlaying': 'खेलना बंद करें',
    'instructions.title': 'कैसे खेलें',
    'instructions.guessYear': 'वर्ष का अनुमान लगाएं: उस वर्ष को टाइप करें जब राष्ट्रपति ने अपना कार्यकाल शुरू किया था।',
    'instructions.guessSuccessor': 'उत्तराधिकारी का अनुमान लगाएं: उस राष्ट्रपति का चयन करें जो उनके बाद आया।',
    'instructions.guessPresident': 'राष्ट्रपति का अनुमान लगाएं: सुराग के आधार पर राष्ट्रपति की पहचान करें।',
    'instructions.close': 'बंद करें',
    'leaderboard.title': 'हॉल ऑफ फेम',
    'leaderboard.loading': 'लोड हो रहा है...',
    'leaderboard.noScores': 'अभी तक कोई स्कोर नहीं। पहले बनें!',
    'leaderboard.rank': 'रैंक',
    'leaderboard.name': 'नाम',
    'leaderboard.score': 'स्कोर',
    'leaderboard.time': 'समय शेष',
    'leaderboard.date': 'तारीख',
    'leaderboard.mode': 'मोड',
    'leaderboard.back': 'प्रारंभ पर वापस जाएं',
    'review.title': 'समीक्षा मोड',
    'review.back': 'प्रारंभ पर वापस जाएं',
    'review.search': 'राष्ट्रपतियों की खोज करें...',
    'review.term': 'कार्यकाल: {start} - {end}',
    'review.noResults': 'कोई राष्ट्रपति नहीं मिला',
    'review.adjustFilters': 'अपने फ़िल्टर समायोजित करने का प्रयास करें।',
    'review.searchName': '1. नाम से खोजें',
    'review.searchNamePlaceholder': 'उदा., लिंकन',
    'review.searchDates': '2. तिथियों से खोजें',
    'review.searchFrom': 'से (उदा., 1800)',
    'review.searchTo': 'तक (उदा., 1850)',
    'review.searchPeriod': '3. अवधि खोजें',
    'review.allPeriods': 'सभी अवधियाँ',
    'review.clearFilters': 'फ़िल्टर साफ़ करें',
    'review.cancel': 'रद्द करें',
    'review.apply': 'लागू करें',
    'review.advancedSearch': 'उन्नत खोज',
    'review.searchAndFilter': 'खोज और फ़िल्टर',
    'review.foundResults': '{count} परिणाम मिले। अधिक जानने के लिए एक कार्ड पर क्लिक करें।',
    'review.hoverToPause': 'रोकने के लिए होवर करें, या अधिक जानने के लिए एक कार्ड पर क्लिक करें।',
    'review.speed': 'गति',
    'review.noPortrait': 'कोई चित्र नहीं',
    'review.present': 'वर्तमान',
    'card.lessThanYear': '(1 वर्ष से कम)',
    'card.years': '({duration} वर्ष)',
    'card.yearsAndCounting': '({duration} वर्ष और जारी)',
    'card.portraitNotAvailable': 'चित्र उपलब्ध नहीं है',
    'card.pending': 'लंबित',
    'card.changePortrait': 'चित्र बदलें',
    'seal.notAvailable': 'मुहर उपलब्ध नहीं है',
    'seal.changeImage': 'छवि बदलें',
    'privacy.title': 'गोपनीयता नीति',
    'privacy.back': 'प्रारंभ पर वापस जाएं',
    'privacy.lastUpdated': 'अंतिम अद्यतन: 26 अक्टूबर, 2023',
    'privacy.p1': 'यह गोपनीयता नीति सेवा का उपयोग करते समय आपकी जानकारी के संग्रह, उपयोग और प्रकटीकरण पर हमारी नीतियों और प्रक्रियाओं का वर्णन करती है और आपको आपके गोपनीयता अधिकारों और कानून आपको कैसे बचाता है, इसके बारे में बताती है।',
    'privacy.h1': 'व्याख्या और परिभाषाएँ',
    'privacy.p2': 'जिन शब्दों का प्रारंभिक अक्षर बड़ा है, उनके अर्थ निम्नलिखित शर्तों के तहत परिभाषित किए गए हैं। निम्नलिखित परिभाषाओं का अर्थ समान होगा चाहे वे एकवचन या बहुवचन में दिखाई दें।',
    'privacy.h2': 'आपका व्यक्तिगत डेटा एकत्र करना और उसका उपयोग करना',
    'privacy.p3': 'हम कोई व्यक्तिगत डेटा एकत्र नहीं करते हैं। यह एप्लिकेशन क्लाइंट-साइड गेम के रूप में कार्य करता है। खेलते समय गेम की प्रगति आपके ब्राउज़र की मेमोरी में अस्थायी रूप से सहेजी जाती है।',
    'privacy.h3': 'API उपयोग',
    'privacy.p4': 'यह एप्लिकेशन ऐतिहासिक सामग्री उत्पन्न करने के लिए Google Gemini API का उपयोग करता है। जब आप "और जानें" सुविधा का उपयोग करते हैं, तो एप्लिकेशन API को एक संकेत भेजता है। कोई व्यक्तिगत उपयोगकर्ता डेटा नहीं भेजा जाता है।',
    'privacy.h4': 'हमसे संपर्क करें',
    'privacy.p5': 'यदि इस गोपनीयता नीति के बारे में आपके कोई प्रश्न हैं, तो आप हमसे संपर्क कर सकते हैं।',
    'terms.title': 'सेवा की शर्तें',
    'terms.back': 'प्रारंभ पर वापस जाएं',
    'terms.lastUpdated': 'अंतिम अद्यतन: 26 अक्टूबर, 2023',
    'terms.p1': 'कृपया हमारी सेवा का उपयोग करने से पहले इन नियमों और शर्तों को ध्यान से पढ़ें।',
    'terms.h1': 'स्वीकृति',
    'terms.p2': 'ये नियम और शर्तें हैं जो इस सेवा के उपयोग और आपके और कंपनी के बीच संचालित होने वाले समझौते को नियंत्रित करती हैं। ये नियम और शर्तें सेवा के उपयोग के संबंध में सभी उपयोगकर्ताओं के अधिकारों और दायित्वों को निर्धारित करती हैं।',
    'terms.h2': 'सामग्री',
    'terms.p3': 'इस खेल में प्रस्तुत ऐतिहासिक डेटा मनोरंजन और शैक्षिक उद्देश्यों के लिए है। यद्यपि हम सटीकता के लिए प्रयास करते हैं, हम यह गारंटी नहीं दे सकते कि सभी जानकारी पूरी तरह से सटीक या अद्यतित है।',
    'terms.h3': 'बौद्धिक संपदा',
    'terms.p4': 'सेवा और इसकी मूल सामग्री, सुविधाएँ और कार्यक्षमता कंपनी और उसके लाइसेंसकर्ताओं की अनन्य संपत्ति हैं और रहेंगी।',
    'terms.h4': 'समाप्ति',
    'terms.p5': 'हम किसी भी कारण से, बिना किसी पूर्व सूचना या दायित्व के, आपके उपयोग को तुरंत समाप्त या निलंबित कर सकते हैं, जिसमें बिना किसी सीमा के यदि आप इन नियमों और शर्तों का उल्लंघन करते हैं।',
    'rag.loading': 'लोड हो रहा है...',
    'rag.close': 'बंद करें',
    'rag.error': 'डेटा लाने में त्रुटि।',
    'rag.errorDetailed': 'क्षमा करें, मैं इस समय अधिक जानकारी प्राप्त नहीं कर सका। कृपया अपनी API कुंजी और नेटवर्क कनेक्शन की जांच करें।',
    'rag.findingInfo': 'इसके बारे में कुछ शानदार जानकारी ढूँढ रहा हूँ',
    'rag.pleaseWait': 'आपके लिए... कृपया प्रतीक्षा करें।',
    'rag.sources': 'स्रोत',
    'rag.translate': 'अनुवाद करें',
    'rag.translating': 'अनुवाद हो रहा है...',
    'fact.selectPresident': 'एक राष्ट्रपति चुनें...',
    'timeline.correct': 'सही: {year}',
    'timeline.yourGuess': 'आपका अनुमान: {year}',
    'period.earlyRepublic': 'प्रारंभिक गणराज्य',
    'period.civilWar': 'गृह युद्ध और औद्योगीकरण',
    'period.americanCentury': 'अमेरिकी सदी',
    'period.modernAmerica': 'आधुनिक अमेरिका',
  },
  es: {
    'start.title': 'Línea de Tiempo Presidencial',
    'start.subtitle': 'Pon a prueba tus conocimientos sobre los líderes estadounidenses.',
    'start.learn': 'Aprender',
    'start.howToPlay': 'Cómo Jugar',
    'start.reviewMode': 'Modo Repaso',
    'start.play': 'Jugar',
    'start.guessPresident': 'Adivina el Presidente',
    'start.guessYear': 'Adivina el Año',
    'start.guessSuccessor': 'Adivina el Sucesor',
    'start.privacyPolicy': 'Política de Privacidad',
    'start.termsOfService': 'Términos de Servicio',
    'start.feedback': 'Comentarios',
    'start.hallOfFame': 'Salón de la Fama',
    'game.placePresident': 'Coloca a {name} en la línea de tiempo.',
    'game.whoWasSuccessor': '¿Quién fue el sucesor de {name}?',
    'fact.whoIsThis': '¿Quién es este?',
    'game.year': 'Año',
    'game.submit': 'Enviar',
    'scoreboard.score': 'Puntuación: {score}',
    'scoreboard.incorrect': 'Incorrecto: {incorrect}',
    'scoreboard.round': 'Ronda {round} / {totalRounds}',
    'scoreboard.time': 'Tiempo: {time}s',
    'end.gameOver': '¡Juego Terminado!',
    'end.finalScore': 'Puntuación Final: {score} / {totalRounds}',
    'end.totalTimeLeft': 'Tiempo Total Restante: {time}s',
    'end.enterName': 'Ingresa tu nombre para el Salón de la Fama:',
    'end.submitScore': 'Enviar Puntuación',
    'end.playAgain': 'Jugar de Nuevo',
    'end.saving': 'Guardando...',
    'end.globalTop10': '¡Top 10 Global! 🏆',
    'end.greatEffort': '¡Gran esfuerzo! Inténtalo de nuevo para llegar al Top 10 Global.',
    'feedback.correct': '¡Correcto!',
    'feedback.incorrect': '¡Incorrecto!',
    'feedback.timeUp': '¡Se acabó el tiempo!',
    'feedback.yearWas': 'El año era {year}.',
    'feedback.successorWas': 'El sucesor fue {name}.',
    'feedback.presidentWas': 'El presidente fue {name}.',
    'feedback.yearCorrectDesc': '¡Estás en lo cierto! El mandato comenzó en {year}.',
    'feedback.yearIncorrectDesc': 'Adivinaste {guessed}, pero el año correcto era ',
    'feedback.successorCorrectDesc': '{name} fue efectivamente el siguiente presidente.',
    'feedback.successorIncorrectDesc': 'Adivinaste {guessed}, pero el sucesor correcto era ',
    'feedback.presidentCorrectDesc': '¡Así es! Fue {name}.',
    'feedback.presidentIncorrectDesc': 'Adivinaste {guessed}, pero el presidente correcto era ',
    'feedback.didYouKnow': '¿Sabías que?',
    'feedback.unknownPresident': 'Presidente Desconocido',
    'feedback.unknown': 'Desconocido',
    'feedback.nextRound': 'Siguiente Ronda',
    'feedback.learnMore': 'Saber más',
    'feedback.stopPlaying': 'Dejar de jugar',
    'instructions.title': 'Cómo Jugar',
    'instructions.guessYear': 'Adivina el Año: Escribe el año en que el presidente comenzó su mandato.',
    'instructions.guessSuccessor': 'Adivina el Sucesor: Selecciona el presidente que vino después de ellos.',
    'instructions.guessPresident': 'Adivina el Presidente: Identifica al presidente basándote en la pista.',
    'instructions.close': 'Cerrar',
    'leaderboard.title': 'Salón de la Fama',
    'leaderboard.loading': 'Cargando...',
    'leaderboard.noScores': 'Aún no hay puntuaciones. ¡Sé el primero!',
    'leaderboard.rank': 'Rango',
    'leaderboard.name': 'Nombre',
    'leaderboard.score': 'Puntuación',
    'leaderboard.time': 'Tiempo Restante',
    'leaderboard.date': 'Fecha',
    'leaderboard.mode': 'Modo',
    'leaderboard.back': 'Volver al Inicio',
    'review.title': 'Modo Repaso',
    'review.back': 'Volver al Inicio',
    'review.search': 'Buscar presidentes...',
    'review.term': 'Mandato: {start} - {end}',
    'review.noResults': 'No se encontraron presidentes',
    'review.adjustFilters': 'Intenta ajustar tus filtros.',
    'review.searchName': '1. Buscar por Nombre',
    'review.searchNamePlaceholder': 'Ej., Lincoln',
    'review.searchDates': '2. Buscar por Fechas',
    'review.searchFrom': 'Desde (Ej., 1800)',
    'review.searchTo': 'Hasta (Ej., 1850)',
    'review.searchPeriod': '3. Buscar por Época',
    'review.allPeriods': 'Todas las Épocas',
    'review.clearFilters': 'Borrar Filtros',
    'review.cancel': 'Cancelar',
    'review.apply': 'Aplicar',
    'review.advancedSearch': 'Búsqueda Avanzada',
    'review.searchAndFilter': 'Buscar y Filtrar',
    'review.foundResults': 'Se encontraron {count} resultados. Haz clic en una tarjeta para saber más.',
    'review.hoverToPause': 'Pasa el cursor para pausar, o haz clic en una tarjeta para saber más.',
    'review.speed': 'Velocidad',
    'review.noPortrait': 'Sin retrato',
    'review.present': 'Presente',
    'card.lessThanYear': '(Menos de 1 año)',
    'card.years': '({duration} años)',
    'card.yearsAndCounting': '({duration} años y contando)',
    'card.portraitNotAvailable': 'Retrato no disponible',
    'card.pending': 'Pendiente',
    'card.changePortrait': 'Cambiar Retrato',
    'seal.notAvailable': 'Sello no disponible',
    'seal.changeImage': 'Cambiar Imagen',
    'privacy.title': 'Política de Privacidad',
    'privacy.back': 'Volver al Inicio',
    'privacy.lastUpdated': 'Última actualización: 26 de octubre de 2023',
    'privacy.p1': 'Esta Política de Privacidad describe nuestras políticas y procedimientos sobre la recopilación, uso y divulgación de su información al utilizar el Servicio y le informa sobre sus derechos de privacidad y cómo la ley lo protege.',
    'privacy.h1': 'Interpretación y Definiciones',
    'privacy.p2': 'Las palabras cuya letra inicial está en mayúscula tienen significados definidos bajo las siguientes condiciones. Las siguientes definiciones tendrán el mismo significado independientemente de si aparecen en singular o en plural.',
    'privacy.h2': 'Recopilación y Uso de sus Datos Personales',
    'privacy.p3': 'No recopilamos ningún dato personal. Esta aplicación funciona como un juego del lado del cliente. El progreso del juego se guarda temporalmente en la memoria de su navegador mientras juega.',
    'privacy.h3': 'Uso de la API',
    'privacy.p4': 'Esta aplicación utiliza la API de Google Gemini para generar contenido histórico. Cuando utiliza la función "Saber más", la aplicación envía un mensaje a la API. No se envían datos personales del usuario.',
    'privacy.h4': 'Contáctenos',
    'privacy.p5': 'Si tiene alguna pregunta sobre esta Política de Privacidad, puede contactarnos.',
    'terms.title': 'Términos de Servicio',
    'terms.back': 'Volver al Inicio',
    'terms.lastUpdated': 'Última actualización: 26 de octubre de 2023',
    'terms.p1': 'Lea atentamente estos términos y condiciones antes de utilizar nuestro Servicio.',
    'terms.h1': 'Reconocimiento',
    'terms.p2': 'Estos son los Términos y Condiciones que rigen el uso de este Servicio y el acuerdo que opera entre usted y la Compañía. Estos Términos y Condiciones establecen los derechos y obligaciones de todos los usuarios con respecto al uso del Servicio.',
    'terms.h2': 'Contenido',
    'terms.p3': 'Los datos históricos presentados en este juego son para fines de entretenimiento y educación. Si bien nos esforzamos por lograr precisión, no podemos garantizar que toda la información sea completamente exacta o esté actualizada.',
    'terms.h3': 'Propiedad Intelectual',
    'terms.p4': 'El Servicio y su contenido original, características y funcionalidad son y seguirán siendo propiedad exclusiva de la Compañía y sus licenciantes.',
    'terms.h4': 'Terminación',
    'terms.p5': 'Podemos terminar o suspender su acceso inmediatamente, sin previo aviso ni responsabilidad, por cualquier motivo, incluyendo sin limitación si incumple estos Términos y Condiciones.',
    'rag.loading': 'Cargando...',
    'rag.close': 'Cerrar',
    'rag.error': 'Error al obtener datos.',
    'rag.errorDetailed': 'Lo sentimos, no pude obtener más información en este momento. Por favor, compruebe su clave API y su conexión de red.',
    'rag.findingInfo': 'Buscando información brillante sobre',
    'rag.pleaseWait': 'para ti... por favor espera.',
    'rag.sources': 'Fuentes',
    'rag.translate': 'Traducir',
    'rag.translating': 'Traduciendo...',
    'fact.selectPresident': 'Selecciona un presidente...',
    'timeline.correct': 'Correcto: {year}',
    'timeline.yourGuess': 'Tu suposición: {year}',
    'period.earlyRepublic': 'República Temprana',
    'period.civilWar': 'Guerra Civil e Industrialización',
    'period.americanCentury': 'El Siglo Americano',
    'period.modernAmerica': 'América Moderna',
  },
  zh: {
    'start.title': '总统时间线',
    'start.subtitle': '测试您对美国领导人的了解。',
    'start.learn': '学习',
    'start.howToPlay': '怎么玩',
    'start.reviewMode': '复习模式',
    'start.play': '开始游戏',
    'start.guessPresident': '猜总统',
    'start.guessYear': '猜年份',
    'start.guessSuccessor': '猜继任者',
    'start.privacyPolicy': '隐私政策',
    'start.termsOfService': '服务条款',
    'start.feedback': '反馈',
    'start.hallOfFame': '名人堂',
    'game.placePresident': '将 {name} 放在时间线上。',
    'game.whoWasSuccessor': '{name} 的继任者是谁？',
    'fact.whoIsThis': '这是谁？',
    'game.year': '年份',
    'game.submit': '提交',
    'scoreboard.score': '得分: {score}',
    'scoreboard.incorrect': '错误: {incorrect}',
    'scoreboard.round': '第 {round} 轮 / 共 {totalRounds} 轮',
    'scoreboard.time': '时间: {time}秒',
    'end.gameOver': '游戏结束！',
    'end.finalScore': '最终得分: {score} / {totalRounds}',
    'end.totalTimeLeft': '剩余总时间: {time}秒',
    'end.enterName': '输入您的名字以进入名人堂：',
    'end.submitScore': '提交得分',
    'end.playAgain': '再玩一次',
    'end.saving': '保存中...',
    'end.globalTop10': '全球前10名！ 🏆',
    'end.greatEffort': '再接再厉！再试一次以进入全球前10名。',
    'feedback.correct': '正确！',
    'feedback.incorrect': '错误！',
    'feedback.timeUp': '时间到！',
    'feedback.yearWas': '年份是 {year}。',
    'feedback.successorWas': '继任者是 {name}。',
    'feedback.presidentWas': '总统是 {name}。',
    'feedback.yearCorrectDesc': '完全正确！任期始于 {year} 年。',
    'feedback.yearIncorrectDesc': '您猜的是 {guessed}，但正确的年份是 ',
    'feedback.successorCorrectDesc': '{name} 确实是下一任总统。',
    'feedback.successorIncorrectDesc': '您猜的是 {guessed}，但正确的继任者是 ',
    'feedback.presidentCorrectDesc': '没错！是 {name}。',
    'feedback.presidentIncorrectDesc': '您猜的是 {guessed}，但正确的总统是 ',
    'feedback.didYouKnow': '您知道吗？',
    'feedback.unknownPresident': '未知总统',
    'feedback.unknown': '未知',
    'feedback.nextRound': '下一轮',
    'feedback.learnMore': '了解更多',
    'feedback.stopPlaying': '停止游戏',
    'instructions.title': '怎么玩',
    'instructions.guessYear': '猜年份：输入总统开始任期的年份。',
    'instructions.guessSuccessor': '猜继任者：选择接替他们的总统。',
    'instructions.guessPresident': '猜总统：根据线索识别总统。',
    'instructions.close': '关闭',
    'leaderboard.title': '名人堂',
    'leaderboard.loading': '加载中...',
    'leaderboard.noScores': '暂无得分。成为第一名吧！',
    'leaderboard.rank': '排名',
    'leaderboard.name': '名字',
    'leaderboard.score': '得分',
    'leaderboard.time': '剩余时间',
    'leaderboard.date': '日期',
    'leaderboard.mode': '模式',
    'leaderboard.back': '返回主页',
    'review.title': '复习模式',
    'review.back': '返回主页',
    'review.search': '搜索总统...',
    'review.term': '任期: {start} - {end}',
    'review.noResults': '未找到总统',
    'review.adjustFilters': '请尝试调整您的过滤器。',
    'review.searchName': '1. 按名字搜索',
    'review.searchNamePlaceholder': '例如：林肯',
    'review.searchDates': '2. 按日期搜索',
    'review.searchFrom': '从 (例如：1800)',
    'review.searchTo': '至 (例如：1850)',
    'review.searchPeriod': '3. 搜索时期',
    'review.allPeriods': '所有时期',
    'review.clearFilters': '清除过滤器',
    'review.cancel': '取消',
    'review.apply': '应用',
    'review.advancedSearch': '高级搜索',
    'review.searchAndFilter': '搜索和过滤',
    'review.foundResults': '找到 {count} 个结果。点击卡片了解更多。',
    'review.hoverToPause': '悬停以暂停，或点击卡片了解更多。',
    'review.speed': '速度',
    'review.noPortrait': '无画像',
    'review.present': '至今',
    'card.lessThanYear': '(不到1年)',
    'card.years': '({duration} 年)',
    'card.yearsAndCounting': '({duration} 年，仍在继续)',
    'card.portraitNotAvailable': '画像不可用',
    'card.pending': '待定',
    'card.changePortrait': '更改画像',
    'seal.notAvailable': '印章不可用',
    'seal.changeImage': '更改图片',
    'privacy.title': '隐私政策',
    'privacy.back': '返回主页',
    'privacy.lastUpdated': '最后更新：2023年10月26日',
    'privacy.p1': '本隐私政策描述了我们在您使用服务时收集、使用和披露您信息的政策和程序，并告知您的隐私权以及法律如何保护您。',
    'privacy.h1': '解释和定义',
    'privacy.p2': '首字母大写的单词在以下条件下具有定义的含义。无论以单数还是复数形式出现，以下定义均具有相同的含义。',
    'privacy.h2': '收集和使用您的个人数据',
    'privacy.p3': '我们不收集任何个人数据。此应用程序作为客户端游戏运行。游戏进度在您玩游戏时临时保存在浏览器的内存中。',
    'privacy.h3': 'API 使用',
    'privacy.p4': '此应用程序使用 Google Gemini API 生成历史内容。当您使用“了解更多”功能时，应用程序会向 API 发送提示。不会发送任何个人用户数据。',
    'privacy.h4': '联系我们',
    'privacy.p5': '如果您对本隐私政策有任何疑问，可以联系我们。',
    'terms.title': '服务条款',
    'terms.back': '返回主页',
    'terms.lastUpdated': '最后更新：2023年10月26日',
    'terms.p1': '在使用我们的服务之前，请仔细阅读这些条款和条件。',
    'terms.h1': '确认',
    'terms.p2': '这些是管理本服务使用的条款和条件，以及您与公司之间运作的协议。这些条款和条件规定了所有用户在使用服务方面的权利和义务。',
    'terms.h2': '内容',
    'terms.p3': '本游戏中呈现的历史数据仅供娱乐和教育目的。虽然我们努力确保准确性，但我们不能保证所有信息都是完全准确或最新的。',
    'terms.h3': '知识产权',
    'terms.p4': '服务及其原创内容、特性和功能是并将继续是公司及其许可方的专有财产。',
    'terms.h4': '终止',
    'terms.p5': '我们可能会出于任何原因（包括但不限于您违反本条款和条件）立即终止或暂停您的访问，而无需事先通知或承担责任。',
    'rag.loading': '加载中...',
    'rag.close': '关闭',
    'rag.error': '获取数据时出错。',
    'rag.errorDetailed': '抱歉，目前无法获取更多信息。请检查您的 API 密钥和网络连接。',
    'rag.findingInfo': '正在为您寻找关于',
    'rag.pleaseWait': '的精彩信息... 请稍候。',
    'rag.sources': '来源',
    'rag.translate': '翻译',
    'rag.translating': '翻译中...',
    'fact.selectPresident': '选择一位总统...',
    'timeline.correct': '正确: {year}',
    'timeline.yourGuess': '您的猜测: {year}',
    'period.earlyRepublic': '早期共和国',
    'period.civilWar': '内战与工业化',
    'period.americanCentury': '美国世纪',
    'period.modernAmerica': '现代美国',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language][key as keyof typeof translations['en']] || key;
    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, String(params[param]));
      });
    }
    return text;
  };

  const getPresidentTranslation = (id: number, field: 'title' | 'context', fallback: string) => {
    if (language === 'fr' && presidents_fr[id]) {
      return presidents_fr[id][field];
    }
    if (language === 'ja' && presidents_ja[id]) {
      return presidents_ja[id][field];
    }
    if (language === 'ar' && presidents_ar[id]) {
      return presidents_ar[id][field];
    }
    if (language === 'hi' && presidents_hi[id]) {
      return presidents_hi[id][field];
    }
    if (language === 'es' && presidents_es[id]) {
      return presidents_es[id][field];
    }
    if (language === 'zh' && presidents_zh[id]) {
      return presidents_zh[id][field];
    }
    return fallback;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getPresidentTranslation }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
